CC = g++
CFLAGS = -Wall -g -std=c++11

INCLUDES = -I../include

LFLAGS = 
#-L../lib

LIBS = 
#-lmylib -lm

SRCS = main.cpp error.cpp scanner.cpp lexer.cpp parser.cpp statement.cpp interpreter.cpp object.cpp data.cpp

OBJS = $(SRCS:.c=.o)

# define the executable file 
MAIN = slc

#
# The following part of the makefile is generic; it can be used to 
# build any executable just by changing the definitions above and by
# deleting dependencies appended to the file from 'make depend'
#



.PHONY: depend clean

all:    $(MAIN)

$(MAIN): $(OBJS) 
		$(CC) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)

.c.o:
		$(CC) $(CFLAGS) $(INCLUDES) -c $<  -o $@

clean:
		$(RM) *.o *~ $(MAIN)
		$(RM) -r *.dSYM
		$(RM) *.exe 

depend: $(SRCS)
		makedepend $(INCLUDES) $^

# DO NOT DELETE THIS LINE -- make depend needs it
